name: Backblaze B2 Sync

on:
  push:
    branches:
      - main

jobs:
  backblaze-cli-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install b2 CLI tool
        run: |
          pip install b2 --log /dev/null

      - name: List files in Backblaze B2 bucket
        run: |
          b2 sync --dry-run --compare-versions size --delete ./src/ "b2://ozoniusswebsite/"

        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
